######################################################################
# Automatically generated by qmake (2.00a) þÔ× á×Ç 24 22:31:53 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += example.h pdatepicker.h pmuffledobject.h
SOURCES += example.cpp main.cpp pdatepicker.cpp
